### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by Sabre142** [fjaros/IgnoreLevel-2.4.3#3]
[Deleted]

**Comment by fjaros** [comment]
I have been thinking about a way to do this but it is not so simple because currently lvl 1 characters can send mail, so level filtering will not work. Plus you wouldn't want that anyway since it would block alt banks. One option is to add a feature which deletes mail if it has no money/items but it would only be a matter of time before bots would send you 1 copper or some useless item.

Would be happy to hear suggestions.
